In [1]:
import pandas as pd
import numpy as np
import seaborn as sns

In [2]:
df = sns.load_dataset('titanic')

In [3]:
print(df.head())

   survived  pclass     sex   age  sibsp  parch     fare embarked  class  \
0         0       3    male  22.0      1      0   7.2500        S  Third   
1         1       1  female  38.0      1      0  71.2833        C  First   
2         1       3  female  26.0      0      0   7.9250        S  Third   
3         1       1  female  35.0      1      0  53.1000        S  First   
4         0       3    male  35.0      0      0   8.0500        S  Third   

     who  adult_male deck  embark_town alive  alone  
0    man        True  NaN  Southampton    no  False  
1  woman       False    C    Cherbourg   yes  False  
2  woman       False  NaN  Southampton   yes   True  
3  woman       False    C  Southampton   yes  False  
4    man        True  NaN  Southampton    no   True  


In [4]:
print(df.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 15 columns):
 #   Column       Non-Null Count  Dtype   
---  ------       --------------  -----   
 0   survived     891 non-null    int64   
 1   pclass       891 non-null    int64   
 2   sex          891 non-null    object  
 3   age          714 non-null    float64 
 4   sibsp        891 non-null    int64   
 5   parch        891 non-null    int64   
 6   fare         891 non-null    float64 
 7   embarked     889 non-null    object  
 8   class        891 non-null    category
 9   who          891 non-null    object  
 10  adult_male   891 non-null    bool    
 11  deck         203 non-null    category
 12  embark_town  889 non-null    object  
 13  alive        891 non-null    object  
 14  alone        891 non-null    bool    
dtypes: bool(2), category(2), float64(2), int64(4), object(5)
memory usage: 80.7+ KB
None


In [5]:
rdf = df.drop(['deck', 'embark_town'], axis = 1)
print(rdf.columns.values)

['survived' 'pclass' 'sex' 'age' 'sibsp' 'parch' 'fare' 'embarked' 'class'
 'who' 'adult_male' 'alive' 'alone']


In [6]:
rdf = rdf.dropna(subset = ['age'], how = 'any', axis = 0)

In [7]:
len(rdf)

714

In [8]:
most_freq = rdf['embarked'].value_counts(dropna=True).idxmax()

In [9]:
most_freq

'S'

In [10]:
rdf.describe(include='all')

survived      pclass   sex         age       sibsp       parch  \
count   714.000000  714.000000   714  714.000000  714.000000  714.000000   
unique         NaN         NaN     2         NaN         NaN         NaN   
top            NaN         NaN  male         NaN         NaN         NaN   
freq           NaN         NaN   453         NaN         NaN         NaN   
mean      0.406162    2.236695   NaN   29.699118    0.512605    0.431373   
std       0.491460    0.838250   NaN   14.526497    0.929783    0.853289   
min       0.000000    1.000000   NaN    0.420000    0.000000    0.000000   
25%       0.000000    1.000000   NaN   20.125000    0.000000    0.000000   
50%       0.000000    2.000000   NaN   28.000000    0.000000    0.000000   
75%       1.000000    3.000000   NaN   38.000000    1.000000    1.000000   
max       1.000000    3.000000   NaN   80.000000    5.000000    6.000000   

              fare embarked  class  who adult_male alive alone  
count   714.000000      712    714  714        714   714   714  
unique         NaN        3      3    3          2     2     2  
top            NaN        S  Third  man       True    no  True  
freq           NaN      554    355  413        413   424   404  
mean     34.694514      NaN    NaN  NaN        NaN   NaN   NaN  
std      52.918930      NaN    NaN  NaN        NaN   NaN   NaN  
min       0.000000      NaN    NaN  NaN        NaN   NaN   NaN  
25%       8.050000      NaN    NaN  NaN        NaN   NaN   NaN  
50%      15.741700      NaN    NaN  NaN        NaN   NaN   NaN  
75%      33.375000      NaN    NaN  NaN        NaN   NaN   NaN  
max     512.329200      NaN    NaN  NaN        NaN   NaN   NaN

In [11]:
rdf['embarked'].fillna(most_freq, inplace = True)

In [12]:
rdf['embarked']

0      S
1      C
2      S
3      S
4      S
      ..
885    Q
886    S
887    S
889    C
890    Q
Name: embarked, Length: 714, dtype: object

In [13]:
ndf = rdf[['survived', 'pclass', 'sex', 'age', 'sibsp', 'parch', 'embarked']]

In [14]:
ndf

survived  pclass     sex   age  sibsp  parch embarked
0           0       3    male  22.0      1      0        S
1           1       1  female  38.0      1      0        C
2           1       3  female  26.0      0      0        S
3           1       1  female  35.0      1      0        S
4           0       3    male  35.0      0      0        S
..        ...     ...     ...   ...    ...    ...      ...
885         0       3  female  39.0      0      5        Q
886         0       2    male  27.0      0      0        S
887         1       1  female  19.0      0      0        S
889         1       1    male  26.0      0      0        C
890         0       3    male  32.0      0      0        Q

[714 rows x 7 columns]

In [15]:
ndf.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 714 entries, 0 to 890
Data columns (total 7 columns):
 #   Column    Non-Null Count  Dtype  
---  ------    --------------  -----  
 0   survived  714 non-null    int64  
 1   pclass    714 non-null    int64  
 2   sex       714 non-null    object 
 3   age       714 non-null    float64
 4   sibsp     714 non-null    int64  
 5   parch     714 non-null    int64  
 6   embarked  714 non-null    object 
dtypes: float64(1), int64(4), object(2)
memory usage: 44.6+ KB


In [16]:
onehot_sex = pd.get_dummies(ndf['sex'])

In [17]:
ndf = pd.concat([ndf,onehot_sex], axis=1)

In [18]:
onehot_embarked = pd.get_dummies(ndf['embarked'], prefix='town')

In [19]:
ndf = pd.concat([ndf, onehot_embarked], axis=1)

In [20]:
ndf.head()

survived  pclass     sex   age  sibsp  parch embarked  female  male  \
0         0       3    male  22.0      1      0        S       0     1   
1         1       1  female  38.0      1      0        C       1     0   
2         1       3  female  26.0      0      0        S       1     0   
3         1       1  female  35.0      1      0        S       1     0   
4         0       3    male  35.0      0      0        S       0     1   

   town_C  town_Q  town_S  
0       0       0       1  
1       1       0       0  
2       0       0       1  
3       0       0       1  
4       0       0       1

In [21]:
ndf.drop(['sex', 'embarked'], axis = 1, inplace = True)

In [22]:
ndf.head()

survived  pclass   age  sibsp  parch  female  male  town_C  town_Q  town_S
0         0       3  22.0      1      0       0     1       0       0       1
1         1       1  38.0      1      0       1     0       1       0       0
2         1       3  26.0      0      0       1     0       0       0       1
3         1       1  35.0      1      0       1     0       0       0       1
4         0       3  35.0      0      0       0     1       0       0       1

In [23]:
x = ndf[['pclass', 'age', 'sibsp', 'parch', 'female', 'male', 'town_C', 'town_Q', 'town_S']]
y = ndf.survived

In [24]:
from sklearn import preprocessing
x = preprocessing.StandardScaler().fit(x).transform(x)

In [25]:
from sklearn.model_selection import train_test_split
x_train, x_test, y_train, y_test = train_test_split(x, y, test_size=0.3, random_state=10)

In [26]:
x_train.shape

(499, 9)

In [27]:
x_test.shape

(215, 9)

In [28]:
from sklearn.neighbors import KNeighborsClassifier

In [29]:
knn = KNeighborsClassifier(n_neighbors=5)

In [30]:
knn.fit(x_train, y_train.values.ravel())

KNeighborsClassifier()

In [31]:
y_hat = knn.predict(x_test)

In [32]:
print(y_hat[0:10])
print(y_test.values[0:10])

[0 0 1 0 0 1 1 1 0 0]
[0 0 1 0 0 1 1 1 0 0]


In [33]:
from sklearn import metrics
knn_matrix = metrics.confusion_matrix(y_test, y_hat)
print(knn_matrix)

knn_report = metrics.classification_report(y_test, y_hat)
print(knn_report)

[[111  14]
 [ 24  66]]
              precision    recall  f1-score   support

           0       0.82      0.89      0.85       125
           1       0.82      0.73      0.78        90

    accuracy                           0.82       215
   macro avg       0.82      0.81      0.82       215
weighted avg       0.82      0.82      0.82       215



In [34]:
df = pd.read_csv('https://archive.ics.uci.edu/ml/machine-learning-databases/breast-cancer-wisconsin/breast-cancer-wisconsin.data')

In [35]:
df.columns = ['id', 'clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'bare_nuclei', 'chromatin', 'normal_nucleoli', 'mitoses', 'class']

In [36]:
df.head()

id  clump  cell_size  cell_shape  adhesion  epithlial bare_nuclei  \
0  1002945      5          4           4         5          7          10   
1  1015425      3          1           1         1          2           2   
2  1016277      6          8           8         1          3           4   
3  1017023      4          1           1         3          2           1   
4  1017122      8         10          10         8          7          10   

   chromatin  normal_nucleoli  mitoses  class  
0          3                2        1      2  
1          3                1        1      2  
2          3                7        1      2  
3          3                1        1      2  
4          9                7        1      4

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 698 entries, 0 to 697
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype 
---  ------           --------------  ----- 
 0   id               698 non-null    int64 
 1   clump            698 non-null    int64 
 2   cell_size        698 non-null    int64 
 3   cell_shape       698 non-null    int64 
 4   adhesion         698 non-null    int64 
 5   epithlial        698 non-null    int64 
 6   bare_nuclei      698 non-null    object
 7   chromatin        698 non-null    int64 
 8   normal_nucleoli  698 non-null    int64 
 9   mitoses          698 non-null    int64 
 10  class            698 non-null    int64 
dtypes: int64(10), object(1)
memory usage: 60.1+ KB


In [38]:
df.describe()

id       clump   cell_size  cell_shape    adhesion  \
count  6.980000e+02  698.000000  698.000000  698.000000  698.000000   
mean   1.071807e+06    4.416905    3.137536    3.210602    2.809456   
std    6.175323e+05    2.817673    3.052575    2.972867    2.856606   
min    6.163400e+04    1.000000    1.000000    1.000000    1.000000   
25%    8.702582e+05    2.000000    1.000000    1.000000    1.000000   
50%    1.171710e+06    4.000000    1.000000    1.000000    1.000000   
75%    1.238354e+06    6.000000    5.000000    5.000000    4.000000   
max    1.345435e+07   10.000000   10.000000   10.000000   10.000000   

        epithlial   chromatin  normal_nucleoli     mitoses       class  
count  698.000000  698.000000       698.000000  698.000000  698.000000  
mean     3.217765    3.438395         2.869628    1.590258    2.690544  
std      2.215408    2.440056         3.055004    1.716162    0.951596  
min      1.000000    1.000000         1.000000    1.000000    2.000000  
25%      2.000000    2.000000         1.000000    1.000000    2.000000  
50%      2.000000    3.000000         1.000000    1.000000    2.000000  
75%      4.000000    5.000000         4.000000    1.000000    4.000000  
max     10.000000   10.000000        10.000000   10.000000    4.000000

In [39]:
print(df['bare_nuclei'].unique())
print('\n')

df['bare_nuclei'].replace('?', np.nan, inplace=True)
df.dropna(subset = ['bare_nuclei'], axis = 0, inplace=True)
df.bare_nuclei = df.bare_nuclei.astype('int')

['10' '2' '4' '1' '3' '9' '7' '?' '5' '8' '6']




In [40]:
df.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 682 entries, 0 to 697
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   id               682 non-null    int64
 1   clump            682 non-null    int64
 2   cell_size        682 non-null    int64
 3   cell_shape       682 non-null    int64
 4   adhesion         682 non-null    int64
 5   epithlial        682 non-null    int64
 6   bare_nuclei      682 non-null    int64
 7   chromatin        682 non-null    int64
 8   normal_nucleoli  682 non-null    int64
 9   mitoses          682 non-null    int64
 10  class            682 non-null    int64
dtypes: int64(11)
memory usage: 63.9 KB


In [41]:
X = df[['clump', 'cell_size', 'cell_shape', 'adhesion', 'epithlial', 'bare_nuclei', 'chromatin', 'normal_nucleoli', 'mitoses']]

In [42]:
y = df['class']

In [45]:
X = preprocessing.StandardScaler().fit(X).transform(X)

In [46]:
xTrain, xTest, yTrain, yTest = train_test_split(X, y, test_size=0.2, random_state=10)

In [52]:
treeModel = tree.DecisionTreeClassifier(criterion = 'entropy', max_depth = 5)

In [53]:
from sklearn import metrics
from sklearn import tree
from sklearn.model_selection import train_test_split
from sklearn import preprocessing

In [54]:
treeModel.fit(xTrain, yTrain)

DecisionTreeClassifier(criterion='entropy', max_depth=5)

In [56]:
y_hat = treeModel.predict(xTest)

In [58]:
print(y_hat[0:10])
print(yTest.values[0:10])

[4 2 2 4 2 2 2 2 2 2]
[4 2 2 4 2 2 2 2 2 2]


In [ ]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn import preprocessing