# Part 2. 데이터 과학을 위한 파이썬

# 2. 파이썬의 기초

## 2.1 자료형

- 수치형(numerical) : 숫자 형태로 이루어진 수를 나타내는 자료형을 말한다. 일상에서 늘 사용하기 때문에 익숙하다. 자주 쓰이는 수치형 자료는 정수와 부동소수점이 있다.

- 부동소수점 : 소숫점이 움직이는 숫자. 3.14와 같이 소수점이 찍혀 있는 숫자이다. 부동이라는 것은 floating으로 떠서 움직일 수 있음. 고정되어 있지 않다는 것이다

- 문자열 : 문자의 나열을 뜻하는데 문자들의 집합이다. string이라고 불린다

In [1]:
## 정수형 자료형 출력

print(123)
print(7777)

123
7777


In [2]:
## 부동소수점 자료형 출력

print(3.14)
print(-1.2)

3.14
-1.2


In [3]:
## 정수형, 부동소수점 자료형 출력

print(777)
print(3.14)

777
3.14


In [4]:
## type() 함수 출력

print(type(777))
print(type(3.14))

<class 'int'>
<class 'float'>


In [5]:
## 문자열 출력(큰따옴표)

print("Why Learn Python")
print("파이썬을 배워야 하는 이유")

Why Learn Python
파이썬을 배워야 하는 이유


In [6]:
## 문자열 출력(작은따옴표)
print('a')
print('Python is Great for Biginners')

a
Python is Great for Biginners


In [7]:
## 문자열 출력(큰따옴표)

print("""아기 상어 뚜 루루 뚜루
귀여운 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
아기 상어 !
엄마 상어 뚜 루루 뚜루
어여쁜 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
엄마 상어""")

아기 상어 뚜 루루 뚜루
귀여운 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
아기 상어 !
엄마 상어 뚜 루루 뚜루
어여쁜 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
엄마 상어


In [8]:
## 문자열 출력(작은 따옴표)

print('''아빠 상어 뚜 루루 뚜루
힘이 쎈 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
아빠 상어 !
할머니 상어 뚜 루루 뚜루
자상한 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
할머니 상어 !''')

아빠 상어 뚜 루루 뚜루
힘이 쎈 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
아빠 상어 !
할머니 상어 뚜 루루 뚜루
자상한 뚜 루루 뚜루
바닷속 뚜 루루 뚜루
할머니 상어 !


## 2.2 변수

- 변수 : 값(Value)를 저장하는 공간. 숫자 문자 등 모든 자료형 저장 가능. 변수에는 기본적으로 하나의 값만 넣을 수 있다.

In [9]:
## 변수 출력

a = 1
b = '1번만 봐도 변수와 값, 정말 쉽죠 ?'
c = "Tea"
print(a)
print(b)
print(c)

1
1번만 봐도 변수와 값, 정말 쉽죠 ?
Tea


In [10]:
## 숫자 변수형 - count, cnt, counter

cnt = 7
print(cnt)

7


In [11]:
## 문자열 변수명 - string, str

str = "자주 사용되는 문자열 변수명 str, string"
print(str)

자주 사용되는 문자열 변수명 str, string


## 2.3 예약어

- 예약어 : 변수 지정 불가능함. 예약어 유의 사용

In [12]:
## 예약어 출력
import keyword         # keyword라는 모듈 불러오기
print(keyword.kwlist)  # 출력

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


## 2.4 식별자

- 식별자 : 무언가를 식별하기 위해 변수 또는 함수에 주어진 이름을 말한다

### <변수 또는 함수의 이름을 지정하기 전에 식별자로 지정할 수 있는 규칙>
- 첫 문자는 알파벳 문자이거나 언더바(_)여야 한다
- 숫자로 시작할 수 없다
- 특수문자는 언더바(_)만 가능하다.
- 대/소문자를 구분한다. 예를 들어 Hello != hello
- 예약어 사용 불가
- 공백을 포함할 수 없다

## 2.5 리터럴 상수

리터럴 상수 : 1.77 같은 숫자 또는 "Hello Python World"와 같은 문자열을 말한다. 상수는 한번 지정되면 변하지 않는 값이다. 변수와 반대 개념

## 2.6 주석

- 주석 : 프로그램에 영향을 주지 않는 # 뒤에 따라오는 짧은 문장이다

In [13]:
## 간단한 문자열 출력합니다
print("Hello World")   # 문자열 출력

Hello World


## 2.7 표현식과 문장

## 2.8 연산자와 피연산자

In [14]:
## 연산자, 피연산자, 수식 출력

print(1 + 1)
print(2 - 1)
print(3 * 2)
print(4 / 2)
print(12 % 5)

print(2 > 1)
print(3 < 1)

2
1
6
2.0
2
True
False


In [15]:
print(1 <= 4)
print(1 >= 5)
print(7 == 7)
print(3 != 5)

print(3 ** 3)
print(1 + (2 + 5))

True
False
True
True
27
8


## 2.9 문자열

In [16]:
## 문자열 연산자 출력
# 숫자
number1 = 123
number2 = 456
print(number1 + number2)

# 문자열
number1 = '123'
number2 = '456'
print(number1 + number2)

579
123456


### 반복 연산자

In [17]:
## 문열 반복 연산자 출력
# *(곱셈) 연산자로 문자열을 반복한다
print("프로그래밍을 배우고자 하는 입문자들에게 ~ " * 3)
print(3 * "파이썬은 배우기 쉽다 !")

프로그래밍을 배우고자 하는 입문자들에게 ~ 프로그래밍을 배우고자 하는 입문자들에게 ~ 프로그래밍을 배우고자 하는 입문자들에게 ~ 
파이썬은 배우기 쉽다 !파이썬은 배우기 쉽다 !파이썬은 배우기 쉽다 !


### 길이 구하기

In [18]:
## 문자열 길이 출력
im = "HAPPY"
print(len(im))
print(len("쉽게배우는파이썬"))

5
8


In [19]:
## 문자열 슬라이스 출력 - 1
# a라는 이름의 변수에 문자열을 대입합니다
a = "쉽게배우는파이썬"

# 시작과 끝의 범위를 지정합니다
print(a[0:5])
print(a[5:8])
print("HelloPython"[0:5])
print("HelloPython"[5:11])

쉽게배우는
파이썬
Hello
Python


In [20]:
## 문자열 슬라이스 출력 - 2
# a라는 이름의 변수에 문자열을 대입합니다
a = "쉽게배우는파이썬"

# 한쪽 숫자를 생략합니다
print(a[:5])
print(a[5:])
print("HelloPython"[5:])
print("HelloPython"[:5])

쉽게배우는
파이썬
Python
Hello


In [21]:
## 슬라이싱을 활용한 문자열 연결 출력
python = "HelloPython"
python_new = "k" + python[1:]
print(python_new)

kelloPython


## 2.10 불리언 연산자

In [22]:
## 불리언 연산자 출력
# 축구 vs 야구
footbalLove = True     # 축구를 좋아합니다
footbalHate = False    # 축구를 싫어합니다
baseballLove = True    # 야구를 좋아합니다
baseballHate = False   # 야구를 싫어합니다

In [23]:
# 지현 - 축구(True) 야구(False)
print(footbalLove and baseballHate)  # False
print(baseballHate and footbalLove)  # False
print(footbalLove or baseballHate)   # True
print(baseballHate or footbalLove)   # True

False
False
True
True


In [24]:
# 리나 - 축구(False) 야구(True)
print(footbalHate and baseballLove)  # False
print(baseballLove and footbalHate)  # False
print(footbalHate or baseballLove)   # True
print(baseballLove or footbalHate)   # True

False
False
True
True


In [25]:
# 민섭 - 축구(True) 야구(True)
print(footbalLove and baseballLove)  # True
print(baseballLove and footbalLove)  # True
print(footbalLove or baseballLove)   # True
print(baseballLove and footbalLove)  # True

True
True
True
True


In [26]:
# 경록 - 축구(False) 야구(False)
print(footbalHate and baseballHate)  # False
print(baseballHate and footbalHate)  # False
print(footbalHate or baseballHate)   # False
print(baseballHate or footbalHate)   # False

False
False
False
False


## 2.11 in 연산자

In [27]:
## In 연산자 출력
print("h" in "hello")
print("h" in "Hello")

True
False


## 2.12 문자열 비교

In [28]:
## 문자열의 비교 출력
print("hello" == "hello")
print("hello" == "helloo")

print('hello' != "hello")
print('hello' != 'helloo')

True
False
False
True


## 2.13 이스케이프 문자

In [29]:
## 이스케이프 문자 출력
# 이스케이프 문자를 사용하지 않습니다.
print('"파이썬은 배우기 쉽습니다" 라고 말했습니다')
print("'파이썬은 배우기 쉽습니다' 라고 말했습니다")

# 이스케이프 문자를 사용합니다
print("\"파이썬은 배우기 쉽습니다\"라고 말했습니다")
print('\'파이썬은 배우기 쉽습니다\'라고 말했습니다')

"파이썬은 배우기 쉽습니다" 라고 말했습니다
'파이썬은 배우기 쉽습니다' 라고 말했습니다
"파이썬은 배우기 쉽습니다"라고 말했습니다
'파이썬은 배우기 쉽습니다'라고 말했습니다


In [30]:
## 다양한 이스케이프 문자 출력
print("파이썬은 배우기 쉽습니다\n라고 말했습니다")
print("파이썬은 배우기 쉽습니다\t라고 말했습니다")
print("파이썬은 배우기 쉽습니다\\라고 말했습니다")

파이썬은 배우기 쉽습니다
라고 말했습니다
파이썬은 배우기 쉽습니다	라고 말했습니다
파이썬은 배우기 쉽습니다\라고 말했습니다


## 2.14 숫자 연산자

In [31]:
## 사칙연산자 출력
print(1 + 1)
print(2 - 1)
print(3 * 2)
print(4 / 2)


2
1
6
2.0


In [32]:
## 나머지 연산자 출력
print(5 / 3)
print(5 // 3)

1.6666666666666667
1


In [33]:
## 비교/나머지/제곱 연산자 출력
print(12 % 5)
print(2 > 1)
print(3 < 1)
print(1 <= 4)
print(1 >= 5)
print(7 == 7)
print(3 != 5)
print(3 ** 3)
print(1 * (2 + 5))


2
True
False
True
False
True
True
27
7


## 2.15 복합 대입 연산자

In [34]:
## 복합 대입 연산자 - 숫자 출력
num = 10
num += 10
num += 20
num += 30
print('number : ', num)

number :  70


In [35]:
## 복합 대입 연산자 - 문자 출력
str = '안녕하세요'
str += "!"
str += "!"
print("string : ", str)

string :  안녕하세요!!


# 3. 파이썬의 자료형

## 3.1 리스트

In [36]:
## 리스트 출력
list_a = []
list_b = [3, 6, 9, 12, 15]
list_c = ['python', 'is', 'easy', 'to', 'learn']
list_d = [1004, 486, 'happy', 'is', 'the', 'best']
list_e = [7942, ['happy', 'is'], 'the', 'best']
list_f = list(range(1, 10))

print(list_a)
print(list_b)
print(list_c)
print(list_d)
print(list_e)
print(list_f)

[]
[3, 6, 9, 12, 15]
['python', 'is', 'easy', 'to', 'learn']
[1004, 486, 'happy', 'is', 'the', 'best']
[7942, ['happy', 'is'], 'the', 'best']
[1, 2, 3, 4, 5, 6, 7, 8, 9]


In [37]:
## 리스트 - 인덱싱 출력
a = [1, 2, 3]
print(a[0])
print(a[2])
print(a[-1])

1
3
3


In [39]:
## 리스트 - 슬라이싱 출력 1
# 문자열 슬라이스
a = '12345'
print(a[0:2])

# 리스트 슬라이스
b = [1, 2, 3, 4, 5]
print(b[0:2])
c = ['H', 'A', 'P', 'P', 'Y']
print(c[0:2])

12
[1, 2]
['H', 'A']


In [40]:
## 리스트 - 슬라이싱 출력 2
a = [1, 2, 3, 4, 5]
b = a[:2]
c = a[2:]

print(a)
print(b)
print(c)

[1, 2, 3, 4, 5]
[1, 2]
[3, 4, 5]


In [41]:
## 리스트 - 연산자 출력
a = [1, 2, 3]
b = [4, 5, 6]

print(a + b)
print(a * 3)

[1, 2, 3, 4, 5, 6]
[1, 2, 3, 1, 2, 3, 1, 2, 3]


In [43]:
## 리스트 - 요소 추가(append) 출력
a = [1, 2, 3]
a.append(4)
b = ['H', 'A', 'P', 'P']
b.append('Y')

print(a)
print(b)

[1, 2, 3, 4]
['H', 'A', 'P', 'P', 'Y']


In [44]:
## 리스트 - 요소 추가(insert)출력
a = [1, 2, 3]
a.insert(3, 4)
b = ['H', 'A', 'P', 'P']
b.insert(4, 'Y')

print(a)
print(b)

[1, 2, 3, 4]
['H', 'A', 'P', 'P', 'Y']


In [45]:
## 리스트 - 요소 제거 (del)출력
a = [1, 2, 3]
print(a)
del a[1]

b = ['H', 'A', 'P', 'P', 'Y']
print(b)
del b[-1]

print(a)
print(b)

[1, 2, 3]
['H', 'A', 'P', 'P', 'Y']
[1, 3]
['H', 'A', 'P', 'P']


In [46]:
## 리스트 - 요소 제거 (pop) 출력
a = [1, 2, 3, 4]
a.pop(3)
print(a)

b = ['H', 'A', 'P', 'P', 'Y']
b.pop(-1)
print(b)

[1, 2, 3]
['H', 'A', 'P', 'P']


In [47]:
## 리스트 - 내부에 있는지 확인(in 연산자) 출력
# 리스트 선언
list = ['H', 'A', 'P', 'P', 'Y']

print('H' in list)
print('h' in list)

True
False


## 3.2 딕셔너리

In [48]:
# 딕셔너리 출력
dic = {'name' : '서희원', 'phone':'010-6653-7743', 'birthday' : '0923'}

In [49]:
print(dic)

{'name': '서희원', 'phone': '010-6653-7743', 'birthday': '0923'}


In [50]:
dic_a = {1 : 'a', 2 : 'b'}
dic_a[3] = 'c'
print(dic_a)

{1: 'a', 2: 'b', 3: 'c'}


In [51]:
dic_a['name'] = 'Jihyun'
print(dic_a)

{1: 'a', 2: 'b', 3: 'c', 'name': 'Jihyun'}


In [52]:
## 딕셔너리 - 요소 제거하기 출력
del dic_a[1]

In [53]:
print(dic_a)

{2: 'b', 3: 'c', 'name': 'Jihyun'}


## 3.3 튜플

In [54]:
## 튜플 - 요소값을 변경, 삭제하려는 경우 출력
tuple_a = (3, 6, 9, 'python', 'is', 'easy')
del tuple_a[0]

TypeError: 'tuple' object doesn't support item deletion

In [56]:
## 튜플 - 인덱싱, 슬라이싱, 더하기, 곱하기, 길이 출력
tuple_a = (3, 6, 9,  12, 15)
tuple_b = ('python', 'is', 'easy', 'to', 'learn')
tuple_c = (1004, 486, 'happy', 'is', 'the', 'best')
tuple_d = (7942, ['happy', 'is'], 'the', 'best')
print(tuple_a[1])          # indexing
print(tuple_b[1:])         # slicing
print(tuple_c + tuple_d)   # +
print(tuple_b * 2)         # *
print(len(tuple_b))        # len

6
('is', 'easy', 'to', 'learn')
(1004, 486, 'happy', 'is', 'the', 'best', 7942, ['happy', 'is'], 'the', 'best')
('python', 'is', 'easy', 'to', 'learn', 'python', 'is', 'easy', 'to', 'learn')
5


# 4. 파이썬의 제어문

## 4.1 조건문

In [58]:
## if 조건문 출력
# 입력값 받기
num = input("정수 입력 : ")
num = int(num)

# 짝수
if num % 2 != 1 :
    print("짝수입니다")
    
# 홀수    
if num % 2 == 1 :
    print("홀수입니다")

정수 입력 : 3
홀수입니다


In [59]:
## else 구문 출력
# 입력값 

# 입력값 받기
num = input("정수 입력 : ")
num = int(num)

if num % 2 != 1 : # 짝수
    print("짝수입니다")
else:             # 홀수
    print('홀수입니다')

정수 입력 : 4
짝수입니다


In [60]:
## elif 구문
# 입력값 받기
month = int(input("계절을 확인할 달을 입력해 주세요 : "))

if 3 <= month <5 :
    print('Spring')
elif 6 <= month <= 8 :
    print('Summer')
elif 9 <= month <= 11 :
    print('Autumn')
else:
    print('winter')

계절을 확인할 달을 입력해 주세요 : 4
Spring


In [61]:
## pass 

month = int(input("계절을 확인할 달을 입력해 주세요 : "))

if 3 <= month <5 :
    pass
elif 6 <= month <= 8 :
    pass
elif 9 <= month <= 11 :
    pass
else:
    pass

계절을 확인할 달을 입력해 주세요 : 3


## 4.2 반복문

In [62]:
## for 반복문 - 리스트와 함께 사용 출력
array = [1, 2, 3, 4, 5, 6]

for var in array:
    print(var)

1
2
3
4
5
6


In [64]:
## for 반복문 - 리스트와 함께 인덱스 출력
array = [1, 2, 3, 4, 5, 6]

for i,var in enumerate(array):
    print("index : ", i, 'List : ', var)

index :  0 List :  1
index :  1 List :  2
index :  2 List :  3
index :  3 List :  4
index :  4 List :  5
index :  5 List :  6


In [65]:
## for 반복문 - 딕셔너리와 함께 사용 출력
dic = {
    'name' : '정지현',
    'phone' : '010-6653-7743',
    'bday' : '0923'
}

In [66]:
for key in dic :
    print(key, dic[key])

name 정지현
phone 010-6653-7743
bday 0923


In [67]:
### while 반복문 출력
i = 1

while i < 5:
    print(i, '번째 반복입니다.')
    i += 1

1 번째 반복입니다.
2 번째 반복입니다.
3 번째 반복입니다.
4 번째 반복입니다.


## 4.3 제어문

In [75]:
## break 출력
i = 1

# 무한 반복입니다
while True :
    # 몇 번째 반복인지 출력합니다
    print(i, '번째 반복입니다.')
    i += 1
    
# 반복을 종료합니다.
    input_text = input("> 종료하시겠습니까? (종료하실 경우 y or Y) : ")
    if input_text == ('y' or 'Y'):
        print('반복을 종료합니다.')
        break

1 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 2
2 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 565
3 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 6
4 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 6
5 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 5
6 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : 6
7 번째 반복입니다.
> 종료하시겠습니까? (종료하실 경우 y or Y) : y
반복을 종료합니다.


In [6]:
## continue 출력
# list
array = list(range(1, 10))

# 반복문을 실행
for number in array :
    
    # 짝수 -> 다음 반복
    if number % 2 == 0:
        continue
    # 출력 

    print('홀수 : ', number)

홀수 :  1
홀수 :  3
홀수 :  5
홀수 :  7
홀수 :  9


# 5. 파이썬의 함수

## 5.1 함수

In [7]:
## 함수의 구조 - 매개변수 없음 출력
# 함수를 선언합니다
def func_print():
    print('Python Programming')
    print('learning about function')
    
# 함수 호출
func_print()

Python Programming
learning about function


## 5.2 매개변수

In [10]:
## 함수의 구조 - 매개변수 있음 출력
# 함수 선언
def multiple_table(n) :
    array= list(range(1,10))
    
    for number in array:
        print(number * n)
        
multiple_table(3)

3
6
9
12
15
18
21
24
27


In [99]:
## 가변 매개변수 출력
# 가변 매개변수
def func_sum(* num) :
    result = 0
    
    for i in num :
        result += i
    print(result)
    
# 매개변수 5개
func_sum(1, 2, 3, 4, 5)

# 매개변수 10개
func_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)

15
55


In [100]:
## 초깃값이 설정된 매개변수 출력
def func_print_return(string, n = 3):
    
    for i in range(n):
        print(i, string)
        
func_print_return("열심히 파이썬을 배우고 있습니다")

0 열심히 파이썬을 배우고 있습니다
1 열심히 파이썬을 배우고 있습니다
2 열심히 파이썬을 배우고 있습니다


## 5.3 반환값 

In [101]:
## 리턴 출력
# 함수 선언
def func_print_return() :
    result = 0
    
    for i in num :
        result += i
    # result반환
    return result

In [102]:
sum = func_sum(1, 2, 3, 4, 5, 6, 7, 8, 9, 10)
print(sum)

55
None


# 7. 넘파이

## 7.1 배열

In [111]:
# ndarray 생셩하기 출력
import numpy as np

# 1차원 형태 Vector
data_1 = [1, 2, 3, 4, 5]

# 2차원 형태 Matric
data_2 = [[1, 2, 3],
         [4, 5, 6]]

data_3 = [[1, 2, 3.0],
         [4, 5.0, 6]]

### 예제

In [113]:
import numpy as np

mid_scores = [10, 20, 30]
final_scores = [70, 80, 90]

total = mid_scores + final_scores

In [114]:
total

[10, 20, 30, 70, 80, 90]

In [116]:
mid_score = np.array([10, 20, 30])
final_score = np.array([70, 80, 90])

In [117]:
total = mid_score + final_score

In [118]:
print("시험 성적의 합계 : ", total)
print("시험 성적의 평균 : ", total / 2)

시험 성적의 합계 :  [ 80 100 120]
시험 성적의 평균 :  [40. 50. 60.]


In [121]:
## ndarray - 배열 생성 함수 출력
print("1) np.zeros(5) : ", np.zeros(5))
print("2) np.zeros((2, 5)) : ", np.zeros((2,5)))
print("3) np.ones(5) : ", np.ones(5))
print("4) np.empty((2, 2, 3)) : ", np.empty((2, 2, 3)))
print("5) np.arange(5) : ", np.arange(5))
print("6) np.full((3, 3), 7) : \n", np.full((3,3),7))

1) np.zeros(5) :  [0. 0. 0. 0. 0.]
2) np.zeros((2, 5)) :  [[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]
3) np.ones(5) :  [1. 1. 1. 1. 1.]
4) np.empty((2, 2, 3)) :  [[[0.00000000e+000 1.00937611e-320 0.00000000e+000]
  [0.00000000e+000 0.00000000e+000 4.47032019e-038]]

 [[5.24889399e-090 5.34962119e-038 4.31752662e-038]
  [2.76998130e-057 3.99910963e+252 1.46030983e-319]]]
5) np.arange(5) :  [0 1 2 3 4]
6) np.full((3, 3), 7) : 
 [[7 7 7]
 [7 7 7]
 [7 7 7]]


## 7.2 인덱싱

In [11]:
## 인덱싱 출력
# 넘파이 모듈 불러오기
import numpy as np

# 1차원 형태입니다
vector_1 = np.array([1, 2, 3, 4, 5])

# 2차원 형태입니다
matrix_2 = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

# 1차원 형태 - 인덱싱 입니다
print("vector_1[1] : ", vector_1[1])
print("vector_1[-1] : ", vector_1[-1])

# 2차원 형태 - 인덱싱 입니다
print('matrix_2[1,1] : ', matrix_2[1, 1])
print('matrix_2[2, -1] : ', matrix_2[2, -1])

vector_1[1] :  2
vector_1[-1] :  5
matrix_2[1,1] :  7
matrix_2[2, -1] :  15


## 7.3 슬라이싱

In [12]:
scores = np.array([88, 72, 93, 94, 89, 78, 99])

In [13]:
scores[1:4]

array([72, 93, 94])

In [14]:
scores[3:]

array([94, 89, 78, 99])

In [15]:
scores[4:-1]

array([89, 78])

In [16]:
## 슬라이싱 - 1차원 출력
# numpy module
import numpy as np

# 1차원 형태입니다
vector = np.array([1, 2, 3, 4, 5])

print(vector[:])
print(vector[:4])
print(vector[1:3])
print(vector[2:])
print(vector[2:-1])

[1 2 3 4 5]
[1 2 3 4]
[2 3]
[3 4 5]
[3 4]


In [4]:
## 슬라이싱 - 2차원 출력
# numpy module
import numpy as np

# 2차원 형태입니다
matrix = np.array([[1, 2, 3, 4, 5],
                    [6, 7, 8, 9, 10],
                    [11, 12, 13, 14, 15],
                    [16, 17, 18, 19, 20],
                    [21, 22, 23, 24, 25]])

print(matrix[:2, 3:], matrix[:2, 3:].shape)

print(matrix[4], matrix[4].shape)
print(matrix[4, :], matrix[4, :].shape)
print(matrix[4:, :], matrix[4:,:].shape)

print(matrix[:,:2], matrix[:,:2].shape)

print(matrix[1, :2], matrix[1, :2].shape)
print(matrix[1:2, :2], matrix[1:2, :2].shape )

[[ 4  5]
 [ 9 10]] (2, 2)
[21 22 23 24 25] (5,)
[21 22 23 24 25] (5,)
[[21 22 23 24 25]] (1, 5)
[[ 1  2]
 [ 6  7]
 [11 12]
 [16 17]
 [21 22]] (5, 2)
[6 7] (2,)
[[6 7]] (1, 2)


## 7.4 통계 및 수학 함수

In [6]:
## 통계 및 수학 함수  출력
# 2차원 형태입니다
matrix = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

print("합 : ", np.sum(matrix))     # sum - np
print("합 : ", matrix.sum())       # sum
print("합 : ", np.mean(matrix))    # mean - np
print("합 : ", matrix.mean())      # mean
print("표준편차 : ", np.std(matrix)) # 표준편차
print("분산 : ", np.var(matrix))    # 분산
print("최댓값 : ", np.max(matrix))   # 최댓값
print("최솟값 : ", np.min(matrix))   # 최솟값

합 :  45
합 :  45
합 :  5.0
합 :  5.0
표준편차 :  2.581988897471611
분산 :  6.666666666666667
최댓값 :  9
최솟값 :  1


In [7]:
# 열과 행에서 최댓값 최솟값을 찾는 경우
# 열에서 찾습니다
print("열에서 최댓값 : ", np.max(matrix, axis=0))
print("열에서 최솟값 : ", np.min(matrix, axis=0))
print("열에서 평균값 : ", np.mean(matrix, axis=0))

# 행에서 찾습니다
print("행에서 최댓값 : ", np.max(matrix, axis=1))
print("행에서 최솟값 : ", np.min(matrix, axis=1))
print("행에서 평균값 : ", np.mean(matrix, axis=1))


열에서 최댓값 :  [7 8 9]
열에서 최솟값 :  [1 2 3]
열에서 평균값 :  [4. 5. 6.]
행에서 최댓값 :  [3 6 9]
행에서 최솟값 :  [1 4 7]
행에서 평균값 :  [2. 5. 8.]


## 7.5 난수 생성

In [2]:
## 난수 생성 함수를 출력
# 난수를 생성합니다
# 초깃값을 설정합니다
import numpy as np
np.random.seed(0)

print("0과 1.0 사이에서 10개의 실수 나눗 생성 : ", np.random.random(10))
print("1부터 45 사이에 6개 정수를 생성합니다. : ", np.random.randint(0, 46, 6))
print("평균이 0.0이고 표준편차가 1.0인 정규분포에서 5개의 수를 뽑음 : ", np.random.normal(0.0, 11.0, 5))
print("1.0보다 크고 5.0 보다 작은 5개의 수를 뽑습니다. : ", np.random.uniform(1.0, 5.0, 5))


print("0.0~1.0 사이의 3개 실수를 랜덤으로 생성합니다.(random_sample) : \n ", np.random.random_sample((3,3)))

0과 1.0 사이에서 10개의 실수 나눗 생성 :  [0.5488135  0.71518937 0.60276338 0.54488318 0.4236548  0.64589411
 0.43758721 0.891773   0.96366276 0.38344152]
1부터 45 사이에 6개 정수를 생성합니다. :  [38 39 23 24 17 37]
평균이 0.0이고 표준편차가 1.0인 정규분포에서 5개의 수를 뽑음 :  [ -5.17848105  10.70317597 -14.05964029  15.81107748  -0.85475023]
1.0보다 크고 5.0 보다 작은 5개의 수를 뽑습니다. :  [4.20364301 3.08190992 3.71551812 3.88253062 3.32807917]
0.0~1.0 사이의 3개 실수를 랜덤으로 생성합니다.(random_sample) : 
  [[0.53737323 0.75861562 0.10590761]
 [0.47360042 0.18633234 0.73691818]
 [0.21655035 0.13521817 0.32414101]]


## 7.6 정렬

In [7]:
## 정렬 - sort()출력
# 난수를 생성기의 시드값에 따라 정해진 난수를 생성합니다
np.random.seed(1)

# 표준편차가 1, 평균값이 0인 정규분포에서 랜덤으로 숫자를 결정합니다
# 1차원 입니다
vector = np.random.randn(5)

print("1차원 배열 sort()정렬 전 : ", vector)
vector.sort()
print("1차원 배열 sort()정렬 후 : ", vector)

# 2차원 입니다
matrix_1 = np.random.randn(5,5)
print("2차원 배열 sort()정렬 전 : \n", matrix_1)
matrix_1.sort()
print("2차원 배열 sort()정렬 후 : \n", matrix_1)

# 특정 축을 기준으로 정렬합니다
matrix_2 = np.random.randn(5, 5)
print("2차원 배열 axis=0축 기준 정렬 전 : \n : ", matrix_2 )
matrix_2.sort(axis=0)
print("2차원 배열 axis=0축 기준 정렬 후 : \n : ", matrix_2 )

matrix_3 = np.random.randn(5, 5)
print("2차원 배열 axis=1축 기준 정렬 전 : \n : ", matrix_3 )
matrix_3.sort(axis=0)
print("2차원 배열 axis=1축 기준 정렬 후 : \n : ", matrix_3 )

# 첫 번째 행만 정렬합니다
matrix_4 = np.random.randn(5, 5)
print('2차원 배열 첫 번째 행만 정렬 전 : \n : ', matrix_4)
matrix_4[:, 0].sort()
print('2차원 배열 첫 번째 행만 정렬 후 : \n : ', matrix_4)


1차원 배열 sort()정렬 전 :  [ 1.62434536 -0.61175641 -0.52817175 -1.07296862  0.86540763]
1차원 배열 sort()정렬 후 :  [-1.07296862 -0.61175641 -0.52817175  0.86540763  1.62434536]
2차원 배열 sort()정렬 전 : 
 [[-2.3015387   1.74481176 -0.7612069   0.3190391  -0.24937038]
 [ 1.46210794 -2.06014071 -0.3224172  -0.38405435  1.13376944]
 [-1.09989127 -0.17242821 -0.87785842  0.04221375  0.58281521]
 [-1.10061918  1.14472371  0.90159072  0.50249434  0.90085595]
 [-0.68372786 -0.12289023 -0.93576943 -0.26788808  0.53035547]]
2차원 배열 sort()정렬 후 : 
 [[-2.3015387  -0.7612069  -0.24937038  0.3190391   1.74481176]
 [-2.06014071 -0.38405435 -0.3224172   1.13376944  1.46210794]
 [-1.09989127 -0.87785842 -0.17242821  0.04221375  0.58281521]
 [-1.10061918  0.50249434  0.90085595  0.90159072  1.14472371]
 [-0.93576943 -0.68372786 -0.26788808 -0.12289023  0.53035547]]
2차원 배열 axis=0축 기준 정렬 전 : 
 :  [[-0.69166075 -0.39675353 -0.6871727  -0.84520564 -0.67124613]
 [-0.0126646  -1.11731035  0.2344157   1.65980218  0.74204416]
 [

In [2]:
## 정렬 - argsort() 출력

# 2차원 배열을 생성합니다
import numpy as np
matrix = np.random.randn(5, 5)
print("랜덤으로 생성합니다. 된 2차원 배열 : \n", matrix)

# 기준이 되는 1차원 배열을 생성합니다
vector = np.array([5, 3, 1, 2, 4])

# matrix 배열이 첫 번째 열에 vector 배열의 요소값을 넣어줍니다
matrix[0] = vector
print("matrix배열의 첫 번째 열에 vector배열의 요소값 대입 : \n ", matrix)
print("argsort()로 정렬된 배열 : \n", matrix[:, matrix[0].argsort()])

랜덤으로 생성합니다. 된 2차원 배열 : 
 [[-1.31778998  0.35714308  0.45707967  1.875644   -1.73899644]
 [ 1.23880498 -1.25338479 -0.58707263  0.02825459  1.71586241]
 [-2.2911804   0.27501037 -0.95155817  1.16239809  0.08127246]
 [-1.46256928  1.1787978  -0.5468846   1.48143431  0.26810084]
 [ 0.8328146   0.9282658   0.56408109 -0.91425236 -0.83099886]]
matrix배열의 첫 번째 열에 vector배열의 요소값 대입 : 
  [[ 5.          3.          1.          2.          4.        ]
 [ 1.23880498 -1.25338479 -0.58707263  0.02825459  1.71586241]
 [-2.2911804   0.27501037 -0.95155817  1.16239809  0.08127246]
 [-1.46256928  1.1787978  -0.5468846   1.48143431  0.26810084]
 [ 0.8328146   0.9282658   0.56408109 -0.91425236 -0.83099886]]
argsort()로 정렬된 배열 : 
 [[ 1.          2.          3.          4.          5.        ]
 [-0.58707263  0.02825459 -1.25338479  1.71586241  1.23880498]
 [-0.95155817  1.16239809  0.27501037  0.08127246 -2.2911804 ]
 [-0.5468846   1.48143431  1.1787978   0.26810084 -1.46256928]
 [ 0.56408109 -0.91425236  0.

## 7.7 배열의 크기 바꾸기

In [3]:
## 배열의 크기 바꾸기 reshape()출력
# (5, 4)
data = [[1, 2, 3 ,4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]

matrix = np.array(data)
print("matrix.shape : ", matrix.shape)

print("matrix.reshape(2, 10) : \n", matrix.reshape(2, 10))

# 주의사항 : 배열의 크기를 변경할 때 행과 열의 개수는 동일해야 합니다
# 따라서 함수를 사용해서 크기를 먼저 사용합니다
print("matrix.size : ", matrix.size)

# reshape 자주 사용되는 -1 매개변수는 해당하는 열의 개수의 맞게 변경해줍니다
print("reshape(1, -1) : \n", matrix.reshape(1, -1))
print("reshape(2, -1) : \n", matrix.reshape(2, -1))
print("reshape(4, -1) : \n", matrix.reshape(4, -1))
print("reshape(5, -1) : \n", matrix.reshape(5, -1))

# 1차원 배열로 변경해줍니다
print("reshape(-1) : \n", matrix.reshape(-1))

matrix.shape :  (5, 4)
matrix.reshape(2, 10) : 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
matrix.size :  20
reshape(1, -1) : 
 [[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]]
reshape(2, -1) : 
 [[ 1  2  3  4  5  6  7  8  9 10]
 [11 12 13 14 15 16 17 18 19 20]]
reshape(4, -1) : 
 [[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]]
reshape(5, -1) : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
reshape(-1) : 
 [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 7.8 벡터나 행렬 전치하기

In [2]:
# 벡터나 행렬 전치 (transpose, swapaxes)출력
data = [[1, 2, 3 ,4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]
import numpy as np
matrix = np.array(data)

print('matrix : \n', matrix)
print("matrix.T : \n", matrix.T)
print("matrix.transpose() : \n", matrix.transpose())
print("np.transpose(matrix) : \n", np.transpose(matrix))
print("matrix.swapaxes(0,1) : \n", matrix.swapaxes(0, 1))
print("matrix 데이터는 복사되지 않았습니다. : \n", matrix)


matrix : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
matrix.T : 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix.transpose() : 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
np.transpose(matrix) : 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix.swapaxes(0,1) : 
 [[ 1  5  9 13 17]
 [ 2  6 10 14 18]
 [ 3  7 11 15 19]
 [ 4  8 12 16 20]]
matrix 데이터는 복사되지 않았습니다. : 
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]


## 7.9 행렬 펼치기

In [3]:
## flatten(행렬 펼치기) 출력 
# (5, 4 구조)
data = [[1, 2, 3 ,4],
        [5, 6, 7, 8],
        [9, 10, 11, 12],
        [13, 14, 15, 16],
        [17, 18, 19, 20]]

matrix = np.array(data)

print(matrix.shape)
print(matrix.flatten())

# flatten()함수를 사용해도 matrix 2차원 배열 자체는 변화가 없습니다.
print(matrix)

# flatten()함수를 사용하면 1차원 배열로 변경됩니다
vec_flatten = matrix.flatten()
print(vec_flatten.ndim)
print(vec_flatten)

(5, 4)
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]
 [17 18 19 20]]
1
[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


## 7.10 산술 연산 및 선형대수

In [4]:
## 산술 연산 및 선형대수 1 출력
# (3, 3)
matrix_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_2 = np.array([[2, 4, 6],
                    [8, 10, 12],
                    [14, 16, 18]])

# 2차원 배열에 사칙 연산을 계산합니다
print(matrix_1 + 2)
print(matrix_1 - 2)
print(matrix_1 / 2)
print(matrix_1 * 2)

# 2차원 배열끼리 사칙연산을 계산합니다
print(matrix_1 + matrix_2)
print(matrix_1 - matrix_2)
print(matrix_1 / matrix_2)
print(matrix_1 * matrix_2)

[[ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]
[[-1  0  1]
 [ 2  3  4]
 [ 5  6  7]]
[[0.5 1.  1.5]
 [2.  2.5 3. ]
 [3.5 4.  4.5]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]
[[ 3  6  9]
 [12 15 18]
 [21 24 27]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[0.5 0.5 0.5]
 [0.5 0.5 0.5]
 [0.5 0.5 0.5]]
[[  2   8  18]
 [ 32  50  72]
 [ 98 128 162]]


In [5]:
## 산술 연산 및 선형대수 2 출력
# (3, 3)
matrix_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_2 = np.array([[2, 4, 6],
                    [8, 10, 12],
                    [14, 16, 18]])

# (3, 0)이 벡터를 더하는 경우입니다
print(matrix_1 + [10, 10, 10])

# (3, 1)이 벡터를 더하는 경우입니다.
print(matrix_1 + [[10], [10], [10]])

# 행렬의 덧셈과 뻴셈입니다
# add와 subtract 함수를 사용합니다
print(np.subtract(matrix_1, matrix_2))
print(np.subtract(matrix_1, matrix_2))

# 행렬의 곱셉입니다
# dot 함수를 사용합니다
print(np.dot(matrix_1, matrix_2))

# @연산자 사용은 파이썬 3.5이상 버전 가능합니다
print(matrix_1 @ matrix_2)

[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[11 12 13]
 [14 15 16]
 [17 18 19]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[-1 -2 -3]
 [-4 -5 -6]
 [-7 -8 -9]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]
[[ 60  72  84]
 [132 162 192]
 [204 252 300]]


## 7.11 불리언

In [8]:
## 배열 간의 비교 연산 출력
# (3, 3)
matrix_1 = np.array([[1, 2, 3],
                    [4, 5, 6],
                    [7, 8, 9]])

matrix_2 = np.array([[2, 4, 6],
                    [8, 10, 12],
                    [14, 16, 18]])

# 배열 간의 비교 연산입니다
print(matrix_1 > matrix_2)
print(matrix_1 >= matrix_2)
print(matrix_1 == matrix_2)
print(matrix_1 != matrix_2)
print(matrix_1 < matrix_2)
print(matrix_1 <= matrix_2)

# 반환한 불리언 배열을 인덱스로 하여 해당 요소값을 확인합니다
print(matrix_1[matrix_1 > matrix_2])
print(matrix_1[matrix_1 >= matrix_2])
print(matrix_1[matrix_1 == matrix_2])
print(matrix_1[matrix_1 != matrix_2])
print(matrix_1[matrix_1 < matrix_2])
print(matrix_1[matrix_1 <= matrix_2])

[[False False False]
 [False False False]
 [False False False]]
[[False False False]
 [False False False]
 [False False False]]
[[False False False]
 [False False False]
 [False False False]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[[ True  True  True]
 [ True  True  True]
 [ True  True  True]]
[]
[]
[]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]
[1 2 3 4 5 6 7 8 9]


In [13]:
## 불리언 값으로 인덱싱
# (10, )
# 1차원 배열 만들기
vector_1 = np.array([70, 71.3, 72.1, 73, 68, 59, 55, 66, 60, 80])
vector_2 = np.array(["하준", '도윤', '준우', '지호', '제균', '시우', '주원', '민준', '지현', '봉기'])

# True, False return
result_bool = vector_1 > 70
print(result_bool)

# return T,F index to find data
print(vector_2[result_bool])

[False  True  True  True False False False False False  True]
['도윤' '준우' '지호' '봉기']


## 예제

In [14]:
heights = [1.83, 1.76, 1.69, 1.86, 1.77, 1.73]
weights = [86, 74,  59, 95, 80, 68]

np.heights = np.array(heights)
np.weights = np.array(weights)

bmi = np.weights/(np.heights ** 2)
print("대상자들의 키 : ", np.heights)
print("대상자들의 몸무게 : ", np.weights)
print("대상자들의 BMI")
print(bmi)

대상자들의 키 :  [1.83 1.76 1.69 1.86 1.77 1.73]
대상자들의 몸무게 :  [86 74 59 95 80 68]
대상자들의 BMI
[25.68007405 23.88946281 20.65754    27.45982194 25.53544639 22.72043837]
