In [1]:
print("Hello Data Science")

Hello Data Science


In [2]:
print(127)

127


In [3]:
print(7777)

7777


In [4]:
import keyword

In [5]:
print(keyword.kwlist)

['False', 'None', 'True', 'and', 'as', 'assert', 'async', 'await', 'break', 'class', 'continue', 'def', 'del', 'elif', 'else', 'except', 'finally', 'for', 'from', 'global', 'if', 'import', 'in', 'is', 'lambda', 'nonlocal', 'not', 'or', 'pass', 'raise', 'return', 'try', 'while', 'with', 'yield']


In [1]:
# import numpy
import numpy as np

# 1차원 형태 Vector
data_1 = [1, 2, 3, 4, 5]

# 2차원 형태 Matric
data_2 = [[1, 2, 3],
         [4, 5, 6]]

data_3 = [[1, 2, 3.0],
         [4, 5.0, 6]]

In [4]:
vector_1 = np.array(data_1)
matrix_1 = np.array(data_2)
matrix_2 = np.array(data_3)

matrix_3 = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

In [5]:
print("vector_1 : ", vector_1)
print("matrix_1 : ", matrix_1)
print("matrix_2 : ", matrix_2)
print("matrix_3 : ", matrix_3)

vector_1 :  [1 2 3 4 5]
matrix_1 :  [[1 2 3]
 [4 5 6]]
matrix_2 :  [[1. 2. 3.]
 [4. 5. 6.]]
matrix_3 :  [[1 2 3]
 [4 5 6]
 [7 8 9]]


In [6]:
import numpy as np
mid_scores = [10, 20, 30]
final_scores = [70, 80, 90]

In [7]:
total = mid_scores + final_scores

In [8]:
total # 리스트가 합쳐져버린다

[10, 20, 30, 70, 80, 90]

In [9]:
mid_scores = np.array([10, 20, 30])
final_scores = np.array([70, 80, 90])

In [10]:
total = mid_scores + final_scores

In [11]:
print("시험 성적의 합계 : ", total)
print("시험 성적의 평균 : ", total/2)

시험 성적의 합계 :  [ 80 100 120]
시험 성적의 평균 :  [40. 50. 60.]


In [3]:
import numpy as np

array_a = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
print('실습 1 : array_a = ', array_a)

실습 1 : array_a =  [0 1 2 3 4 5 6 7 8 9]


In [4]:
array_b = np.array(range(10))
print('실습 2 : array_b = ', array_b)

실습 2 : array_b =  [0 1 2 3 4 5 6 7 8 9]


In [5]:
array_c = np.array(range(0, 10, 2))
print('실습 3 : array_c = ', array_c)

실습 3 : array_c =  [0 2 4 6 8]


In [6]:
print('실습 4 : ')
print('array_c의 shape : ', array_c.shape)
print('array_c의 ndim : ', array_c.ndim)
print('array_c의 dtype : ', array_c.dtype)
print('array_c의 size : ', array_c.size)

실습 4 : 
array_c의 shape :  (5,)
array_c의 ndim :  1
array_c의 dtype :  int64
array_c의 size :  5
